#!/usr/bin/env python3
"""
get _temp version 1.2
Python 3.7
"""

from datetime import datetime
import logging
import requests
import time
from bs4 import BeautifulSoup
from xlwt import Workbook

logging.basicConfig(filename='temp.log', level=logging.DEBUG)

def get_temperature():
    """Gets temperature from web and formats it."""
    page = requests.get("http://bit.ly/3bqVxjP")
    soup = BeautifulSoup(page.content, "html.parser")
    name = soup.find("p", {"class": "myforecast-current-lrg"})

    """Format temperature."""
    current_temp = "".join(name)
    temp_list = list(current_temp)
    del temp_list[2:4]
    logging.debug(temp_list)
    return int("".join(temp_list))


def get_time():
    """gets time of day."""
    now = datetime.now()
    current_time = now.strftime("%H:%M")
    return current_time


def write_temperature():
    """Writes temperature and time at selected interval."""
    seconds = 3600
    col = 0
    row = 0
    wb = Workbook()
    sheet1 = wb.add_sheet("Temp")
    while True:
        print(f"writting at {get_time()}.")
        sheet1.write(row, col, get_temperature())
        sheet1.write(row, 1, get_time())
        wb.save("Temp.xls")
        row += 1
        time.sleep(seconds)


if __name__ == "__main__":
    write_temperature()
